name: CI

on: [push]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - uses: actions/cache@v3
              id: npm-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
            - name: Install packages
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm install

    check:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
            - name: lint
              run: npm run lint:temporary
            - name: format
              run: npm run prettie:check

    contract-test:
        runs-on: ubuntu-latest
        needs: [setup, check]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
            - name: Contract test
              run: npm run test:contract
